# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  tomcatServerPath: '/home/azureuser/apache-tomcat/webapps'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenOptions: '-Xmx1024m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: CopyFiles@2
    inputs:
      contents: '**/*.war'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop'
      downloadPath: '$(System.DefaultWorkingDirectory)'

  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'Tomcat-VM-Connection'   
      sourceFolder: '$(System.DefaultWorkingDirectory)/drop'
      contents: '**/*.war'
      targetFolder: '$(tomcatServerPath)'
      readyTimeout: '20000'
